
import React from 'react';

export const Terms: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4 animate-in">
      <div className="space-y-6">
        <div className="border-b border-border-light pb-4">
          <h1 className="text-3xl font-black tracking-tight text-text-main">Terms of Service</h1>
          <p className="text-text-secondary text-sm mt-1 uppercase tracking-widest font-bold">Effective Date: May 2024</p>
        </div>
        
        <div className="prose prose-sm max-w-none text-text-secondary space-y-4">
          <p className="font-bold text-text-main italic">By using ToolPortal, you agree to these simplified terms.</p>

          <section>
            <h2 className="text-lg font-black text-text-main uppercase tracking-tight">1. Acceptable Use</h2>
            <p className="leading-relaxed">ToolPortal is provided for development, media processing, and general productivity. You may not use the platform for any illegal activities or to generate malicious content using our AI integration.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-text-main uppercase tracking-tight">2. Intellectual Property</h2>
            <p className="leading-relaxed">The code, design, and branding of ToolPortal are the intellectual property of its creators. Output generated by the tools (JSON mocks, resized images, etc.) belongs entirely to you.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-text-main uppercase tracking-tight">3. No Warranty</h2>
            <p className="leading-relaxed">ToolPortal is provided "AS IS" without warranty of any kind. We are not responsible for any data loss, server downtime, or inaccuracies produced by AI-driven tools.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-text-main uppercase tracking-tight">4. Limitation of Liability</h2>
            <p className="leading-relaxed">In no event shall ToolPortal or its operators be liable for any indirect, incidental, or consequential damages arising out of your use of the tools.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-text-main uppercase tracking-tight">5. Modifications</h2>
            <p className="leading-relaxed">We reserve the right to modify these terms or discontinue any feature at any time without prior notice.</p>
          </section>
        </div>
      </div>
    </div>
  );
};
